In [1]:
import numpy as np
import tensorflow as tf

# Task1

In [2]:
i='custid'
a='custname'
b='email'
c='phone'
d='gender'
e='date_of_birth'

cust_record=tf.strings.join([i,a,b,c,d,e],separator=" ~ ")
print(cust_record)

tf.Tensor(b'custid ~ custname ~ email ~ phone ~ gender ~ date_of_birth', shape=(), dtype=string)


# Task2

In [3]:
string=tf.constant(['indigo', 'violet', 'programmer', 'computer', 'training','kitchen',
                  'array', 'instagram', 'bluetooth'])

In [4]:
str_arr=np.array(string).reshape(3,3)
matrix_string=tf.constant(str_arr)
matrix_string

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'indigo', b'violet', b'programmer'],
       [b'computer', b'training', b'kitchen'],
       [b'array', b'instagram', b'bluetooth']], dtype=object)>

# Task3

In [5]:
product_price=tf.constant(1895.2)
product_price

<tf.Tensor: shape=(), dtype=float32, numpy=1895.2>

In [6]:
product_price=tf.cast(product_price,tf.float16)
product_price

<tf.Tensor: shape=(), dtype=float16, numpy=1895.0>

# Task4

In [7]:
marks=tf.Variable(np.zeros((5,3)),dtype=tf.int16)
marks

<tf.Variable 'Variable:0' shape=(5, 3) dtype=int16, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)>

In [8]:
marks.assign(np.random.uniform(36,100,15).reshape(-1,3))

<tf.Variable 'UnreadVariable' shape=(5, 3) dtype=int16, numpy=
array([[76, 49, 38],
       [82, 66, 39],
       [68, 58, 79],
       [94, 78, 92],
       [97, 76, 67]], dtype=int16)>

# Task5

In [12]:
test=tf.Variable(np.zeros((30,5)),dtype=tf.float32)
test

<tf.Variable 'Variable:0' shape=(30, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [18]:
test=tf.cast(test.assign(np.random.uniform(30,100,150).reshape(-1,5)),dtype=tf.float32)

In [20]:
b=tf.constant([0.5,1.5,0.5,1.6,0.8])
c=tf.constant(1.2,dtype=tf.float32)
y=[]
for x in test:
    a=[]
    for i in range(len(x)):
        a.append(b[i]*x[i])
    y.append(sum(a)+c)

In [21]:
y

[<tf.Tensor: shape=(), dtype=float32, numpy=360.4425>,
 <tf.Tensor: shape=(), dtype=float32, numpy=356.07483>,
 <tf.Tensor: shape=(), dtype=float32, numpy=377.12814>,
 <tf.Tensor: shape=(), dtype=float32, numpy=393.31305>,
 <tf.Tensor: shape=(), dtype=float32, numpy=307.77856>,
 <tf.Tensor: shape=(), dtype=float32, numpy=326.69897>,
 <tf.Tensor: shape=(), dtype=float32, numpy=304.11786>,
 <tf.Tensor: shape=(), dtype=float32, numpy=396.62466>,
 <tf.Tensor: shape=(), dtype=float32, numpy=315.2809>,
 <tf.Tensor: shape=(), dtype=float32, numpy=346.85123>,
 <tf.Tensor: shape=(), dtype=float32, numpy=330.5144>,
 <tf.Tensor: shape=(), dtype=float32, numpy=306.47028>,
 <tf.Tensor: shape=(), dtype=float32, numpy=271.36975>,
 <tf.Tensor: shape=(), dtype=float32, numpy=315.25848>,
 <tf.Tensor: shape=(), dtype=float32, numpy=300.2362>,
 <tf.Tensor: shape=(), dtype=float32, numpy=307.28>,
 <tf.Tensor: shape=(), dtype=float32, numpy=343.992>,
 <tf.Tensor: shape=(), dtype=float32, numpy=402.5208>,
 <

# Task6

In [ ]:
currency = {'india':'rupee', 'britain':'dollar','europe':'euro'}
currency

In [ ]:
t_currency = tf.convert_to_tensor(list(currency.items()))

In [ ]:
t_currency

In [ ]:
print(tf.shape(t_currency))
print(tf.size(t_currency))

# Task7

In [ ]:
units= np.random.randint(5,20,4)
units_price= np.round(np.random.uniform(50,100,4),2)
print(units)
print(units_price)

In [ ]:
Total=(units * units_price)
Total